#!/bin/sh

if [ -d /usr/lib/ccache ]; then
    export PATH="/usr/lib/ccache:$PATH"
fi
debian/rules clean 2>&1
dpkg-source --before-build .
CONFIGURE_ARGS="-DCMAKE_BUILD_TYPE=debugfull" debian/rules build 2>&1
dh_auto_test
